export enum ReportReason {
    BREAKS_RULES = 0,
    HARASSMENT = 1,
    HATE = 2,
    SHARING_PERSONAL_INFORMATION = 3,
    IMPERSONATION = 4,
    COPYRIGHT_VIOLATION = 5,
    TRADEMARK_VIOLATION = 6,
    SPAM = 7,
    SELF_HARM_OR_SUICIDE = 8,
    OTHER = 9
}
